### ISSUE TITLE
Using React-Native modal throws error

### ISSUE THREAD

**Issue by exlnt** [creativetimofficial/argon-react-native#22]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

A modal should render upon button click.

# Current Behavior

As soon as the component is requested from the navigration drawer it just crashes.

# Failure Information (for bugs)
See attached image.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create component using attached budget.js code
[Budget.js.txt](https://github.com/creativetimofficial/argon-react-native/files/4640834/Budget.js.txt)

2. Setup this component within Argon UI kit code
3.  Launch the budget component from navigation drawer.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Pixel XL emulator
* Operating System: Windows 
* Browser and Version: Chrome v81

## Failure Logs
See attached image.
![Screenshot_1589742330](https://user-images.githubusercontent.com/13487337/82157569-19b2e880-9837-11ea-8b18-1d682d927b2b.png)

**Comment by palingheorghe** [comment]
Hi! This issue is not related to our product itself. As far as I can see this could be an issue related to one of the components you've created. There should be something in your code creating an "infinite loop" so I think the best thing would be to use the debugger and see where that issue is exactly happening. 

We've updated this product to v1.5.0 and will close this issue. If you think this issue could be related to our product I strongly advise you to update to this new version. 

Thanks!
