### ISSUE TITLE
Something went wrong installing the sharp module

### ISSUE THREAD

**Issue by akash4111998** [creativetimofficial/argon-react-native#3]
![node module error](https://user-images.githubusercontent.com/25797768/59339928-b5340300-8d22-11e9-941d-95409f5b187a.png)

**Comment by palingheorghe** [comment]
Hi @akash4111998, 

Thanks for opening up this issue. Using the issue template would've been more helpful for me in order to be able to identify your problem. Could you please use the issue template? As far as I can see there's a problem with your NodeJs version. You should try and look up the issue on https://github.com/lovell/sharp/issues. 

Thanks,
Alin

**Comment by akash4111998** [comment]
thank you
